### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by ktfleming** [faijdherbe/jira-jump.el#1]
52949ac0ebaa342aac01388e47b186a05b8780d8 removed a lot of code necessary for the package to work, notably the interactive `jira-jump` command and the `(provide 'jira-jump)` form. Was that intentional?

**Comment by faijdherbe** [comment]
I don't think this was intentional.  I'll look into what happened later today.  Thanks for pointing out!

**Comment by faijdherbe** [comment]
Looks like tangling the file failed last time.  Package should work again.
